name: Static Analysis on PHP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  PHPMD:
    name: Run PHPMD scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Install dependencies
        uses: php-actions/composer@v6

      - name: Run PHPMD
        run: vendor/bin/phpmd . text cleancode,codesize,controversial,design,naming,unusedcode --reportfile phpmd-report.txt
        continue-on-error: false

      - name: Upload analysis report
        uses: actions/upload-artifact@v2
        with:
          name: phpmd-report
          path: phpmd-report.txt